#!/usr/bin/bash

display_help() {
	echo
	echo "Usage:"
	echo "   get_bam -i <fastq_location> -s <samples_file>"
	echo
	echo "   -i <fastq_location>        Complete path of the FASTQ files"
	echo "   -s <samples_file>          List of the sample names"
	echo "   -o <output>                Output folder. If not specified, output will be written to the BAM folder at the fastq location "
	echo
	echo "Options:"
	echo "   -h, --help                 Display this help message and exit"
	exit 0
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	display_help
fi

while getopts ":i:s:o:h" opt; do
	case ${opt} in
		i )
			fastq_location=$OPTARG
			;;
		s )
			samples_file=$OPTARG
			;;
		o )
			output=$OPTARG
			;;		
		h )
			display_help
			;;
		\? )
			echo "Invalid option: -$OPTARG" >&2
			display_help
			;;
		: )
			echo "Option -$OPTARG requires an argument." >&2
			display_help
			;;
	esac
done
shift $((OPTIND -1))

if [ -z "$samples_file" ] || [ -z "$fastq_location" ]; then
	echo "Error: Missing required arguments"
	display_help
fi

if [ -n "$output" ]; then
	output_location=$output
else
	output_location="${fastq_location}/BAM"
fi

nextflow -C $PWD/nextflow.config \
run $PWD/fastq_bam.nf \
-entry FASTQ_TO_BAM \
--input ${samples_file} \
--sequences ${fastq_location} \
--output ${output_location} \
-resume -bg 



