#config.yaml for fastq_to_bam_paired.snakefile
#Anna Hoge
#Template made October 18th, 2019
#Ha Lab
#Fred Hutchinson Cancer Research Center

#SELECT CORRECT REFERENCE GENOME
#reference genome for alignment, with index files in same folder as .fa file
reference_genome:
    /home/reference_genomes/hg19_broad/hg19_all.fasta
    #/fh/fast/ha_g/grp/reference/GRCh38/Broad_bundle_hg38/v0/Homo_sapiens_assembly38.fasta

#SELECT CORRECT POLYMORPHIC SITES
#used for rule build_recalibrator_model
#these must have .tbi index files, and the chromosome naming must match the reference file
known_polymorphic_sites1:
    /home/reference_genomes/dbSNPGATK/dbsnp_138.hg19.vcf

known_polymorphic_sites2:
    /home/reference_genomes/dbSNPGATK/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf


#SELECT IF DATA IS WHOLE GENOME SEQUENCES OR NOT (True or False)
#determines if rule get_wgs_metrics is run
is_wgs: False

#SELECT CORRECT BASE RECALIBRATOR GAP OPEN PENALTY
#GATK recommends 40 for exomes and 30 for whole genomes
base_recalibrator_gap_open_penalty: 30.0

#can adjust the number of threads used for bwa based on the data
#suggested this matches cluster_slurm.yaml ncpus for map_to_reference rule
bwa_threads: 4

#tools used.  need to be module loaded first.  see snakemake file for loads
bwa: /home/programs/bwa-0.7.12/bwa
samtools: /home/programs/samtools-1.7/samtools
java: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
gatk: /home/diagnostics/programs/gatk-4.2.6.0/gatk
picard_jar: /home/programs/picard/build/libs/picard.jar
