#samples.yaml for fastq_to_bam_paired.snakefile
#Anna Hoge
#Template made October 18th, 2019
#Ha Lab
#Fred Hutchinson Cancer Research Center

samples: #format is [read1.fq.gz, read2.fq.gz]
  name1: [/home/pipelines/mutation_detector_nextflow/sequences/25NGS187-A1_S48_R1_001.fastq.gz, /home/pipelines/mutation_detector_nextflow/sequences/25NGS187-A1_S48_R2_001.fastq.gz]
  name2: [/home/pipelines/mutation_detector_nextflow/sequences/25NGS187-B1_S49_R1_001.fastq.gz, /home/pipelines/mutation_detector_nextflow/sequences/25NGS187-B1_S49_R2_001.fastq.gz]
