#!/usr/bin/bash

display_help() {
	echo
	echo "Usage:"
	echo "   $0 -i <fastq_location> -s <samples_file> -b <bedfile>"
	echo
	echo "   -i <fastq_location>        Complete path of the FASTQ files"
	echo "   -s <samples_file>          List of the sample names"
	echo "   -b <bedfile>               Complete path of the BED file"
	echo "   -o <output>                Output folder. If not specified, output will be written to the BAM folder at the fastq location "
	echo
	echo "Options:"
	echo "   -h, --help                 Display this help message and exit"
	exit 0
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	display_help
fi

while getopts ":i:s:b:o:h" opt; do
	case ${opt} in
		i )
			fastq_location=$OPTARG
			;;
		s )
			samples_file=$OPTARG
			;;
		b )
			bedfile=$OPTARG
			;;
		o )
			output=$OPTARG
			;;			
		h )
			display_help
			;;
		\? )
			echo "Invalid option: -$OPTARG" >&2
			display_help
			;;
		: )
			echo "Option -$OPTARG requires an argument." >&2
			display_help
			;;
	esac
done
shift $((OPTIND -1))

if [ -z "$samples_file" ] || [ -z "$bedfile" ] || [ -z "$fastq_location" ]; then
	echo "Error: Missing required arguments"
	display_help
fi

if [ -n "$output" ]; then
	output_location=$output
else
	output_location="${fastq_location}/BAM"
fi

nextflow -C /home/diagnostics/pipelines/fastq_to_bam_paired_snakemake/nextflow.config \
run /home/diagnostics/pipelines/fastq_to_bam_paired_snakemake/fastq_bam.nf \
-entry FASTQ_TO_COV \
--bedfile_exonwise ${bedfile} \
--input ${samples_file} \
--sequences ${fastq_location} \
--output ${output_location} \
-resume -bg 

